# Generated by Django 5.0 on 2023-12-10 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(blank=True, max_length=30, unique=True)),
                ('artist', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('POP_MUSIC', 'Pop Music'), ('JAZZ_MUSIC', 'Jazz Music'), ('RNB_MUSIC', 'R&B Music'), ('ROCK_MUSIC', 'Rock Music'), ('COUNTRY_MUSIC', 'Country Music'), ('DANCE_MUSIC', 'Dance Music'), ('HIP_HOP_MUSIC', 'Hip Hop Music'), ('OTHER', 'Other')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
